server:
  port: 8888  # Config Server runs on port 8888 by default

spring:
  cloud:
    config:
      server:
        git:
          uri: file://Users/apple/Desktop/demo-log/config-repo
          default-label: main  # Change this to your Git branch if needed
  application:
    name: config-server
