spring:
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh
